// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RimansaRealEstate.Data;

#nullable disable

namespace RimansaRealEstate.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251206060146_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RimansaRealEstate.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 6, 2, 1, 46, 179, DateTimeKind.Local).AddTicks(360),
                            Email = "admin@rimansa.com",
                            FullName = "Administrador Rimansa",
                            IsActive = true,
                            PasswordHash = "$2a$11$Qy2ew.EE5P.D7DLSbAcTeO.ylL0fxU1Ctm/kY5H.qZxCrJBbrHQQq",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("RimansaRealEstate.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AreaSquareMeters")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<int?>("Bedrooms")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreaSquareMeters = 180m,
                            Bathrooms = 2,
                            Bedrooms = 3,
                            CreatedAt = new DateTime(2025, 12, 6, 2, 1, 46, 180, DateTimeKind.Local).AddTicks(1808),
                            Description = "Hermosa casa moderna con acabados de primera calidad, amplia sala-comedor, cocina equipada y jardín.",
                            ImageUrl = "/images/properties/casa1.jpg",
                            IsActive = true,
                            Location = "Santo Domingo Norte",
                            Price = 250000m,
                            Status = 0,
                            Title = "Casa Moderna en Los Jardines",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            AreaSquareMeters = 120m,
                            Bathrooms = 2,
                            Bedrooms = 2,
                            CreatedAt = new DateTime(2025, 12, 6, 2, 1, 46, 180, DateTimeKind.Local).AddTicks(2141),
                            Description = "Espectacular apartamento con vista panorámica al mar, balcón amplio, y todas las amenidades.",
                            ImageUrl = "/images/properties/apto1.jpg",
                            IsActive = true,
                            Location = "Malecón, Santo Domingo",
                            Price = 1200m,
                            Status = 1,
                            Title = "Apartamento de Lujo Vista al Mar",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            AreaSquareMeters = 500m,
                            CreatedAt = new DateTime(2025, 12, 6, 2, 1, 46, 180, DateTimeKind.Local).AddTicks(2145),
                            Description = "Terreno en zona exclusiva de Bávaro, listo para construir, con todos los servicios disponibles.",
                            ImageUrl = "/images/properties/terreno1.jpg",
                            IsActive = true,
                            Location = "Bávaro, Punta Cana",
                            Price = 85000m,
                            Status = 0,
                            Title = "Terreno Residencial Premium",
                            Type = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
